# Generated by Django 4.2.3 on 2023-08-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_rename_updated_ap_advertisement_updated_ad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Advertisements',
        ),
    ]
